apiVersion: v1
kind: Namespace
metadata:
  name: health
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: health.msfidelis.com.br
spec:
  namespace: health
--- 
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: health.msfidelis.com.br
  namespace: health
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: health-api