apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: arn:aws:iam::181560427716:role/karpenter-cluster-eks-nodes
  securityGroupSelectorTerms: null
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-cluster
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: eks-cluster
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  limits:
    cpu: "100"
    memory: 400Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - c5
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - large
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64