apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative.fullname" . }}-config-observability
  labels:
  {{- include "knative.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}