apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative.fullname" . }}-operator-webhook
  labels:
    app.kubernetes.io/component: operator-webhook
  {{- include "knative.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: operator-webhook
      role: operator-webhook
    {{- include "knative.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: operator-webhook
        app.kubernetes.io/component: operator-webhook
        app.kubernetes.io/name: knative-operator
        app.kubernetes.io/version: 1.15.1
        role: operator-webhook
      {{- include "knative.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: operator-webhook
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.configLoggingName
            }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.configObservabilityName
            }}
        - name: WEBHOOK_NAME
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.webhookName }}
        - name: WEBHOOK_PORT
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.webhookPort }}
        - name: WEBHOOK_SECRET_NAME
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.webhookSecretName
            }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.metricsDomain }}
        - name: KUBERNETES_MIN_VERSION
          value: {{ quote .Values.operatorWebhook.operatorWebhook.env.kubernetesMinVersion
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.operatorWebhook.operatorWebhook.image.repository }}:{{ .Values.operatorWebhook.operatorWebhook.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 1
        name: operator-webhook
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8443
          name: https-webhook
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          periodSeconds: 1
        resources: {{- toYaml .Values.operatorWebhook.operatorWebhook.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.operatorWebhook.operatorWebhook.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "knative.fullname" . }}-operator-webhook
      terminationGracePeriodSeconds: 300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative.fullname" . }}-knative-operator
  labels:
  {{- include "knative.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.knativeOperator.replicas }}
  selector:
    matchLabels:
      name: knative-operator
    {{- include "knative.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knative-operator
        app.kubernetes.io/version: 1.15.1
        name: knative-operator
      {{- include "knative.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_DOMAIN
          value: {{ quote .Values.knativeOperator.knativeOperator.env.metricsDomain }}
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.knativeOperator.knativeOperator.env.configLoggingName
            }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.knativeOperator.knativeOperator.env.configObservabilityName
            }}
        - name: KUBERNETES_MIN_VERSION
          value: {{ quote .Values.knativeOperator.knativeOperator.env.kubernetesMinVersion
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.knativeOperator.knativeOperator.image.repository }}:{{ .Values.knativeOperator.knativeOperator.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.knativeOperator.knativeOperator.imagePullPolicy }}
        name: knative-operator
        ports:
        - containerPort: 9090
          name: metrics
        resources: {}
      serviceAccountName: {{ include "knative.fullname" . }}-knative-operator