apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative.fullname" . }}-knative-serving-operator-aggregated
  labels:
  {{- include "knative.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: serving.knative.dev/release
      operator: Exists
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative.fullname" . }}-knative-serving-operator-aggregated
  labels:
  {{- include "knative.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative.fullname" . }}-knative-serving-operator-aggregated'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'